# Generated by Django 5.1.1 on 2024-10-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
